// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopSolution.Data;

#nullable disable

namespace TopSolution.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230509215841_dataseed")]
    partial class dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TopSolution.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TopicId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TopSolution.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RelatedProgLanguages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "b85d54d2-2a21-459a-9f99-c9fa9bf8d87f",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9774),
                            Description = "Desc 0",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 0",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "3d7ad1c1-9481-4ea2-b707-044f06d6b591",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9870),
                            Description = "Desc 1",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 1",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "d72d7522-b0a4-4a40-abad-b02b2d7cbcda",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9877),
                            Description = "Desc 2",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 2",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "47947215-818c-4333-a4dc-49c4e424d99e",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9884),
                            Description = "Desc 3",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 3",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "eb5e070d-dd01-4356-8942-7cfc9716d05b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9890),
                            Description = "Desc 4",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 4",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "1f50013d-78e8-4fdc-961a-305a09e4ccd2",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9896),
                            Description = "Desc 5",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 5",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "e148417b-b407-4ab8-b77d-46b78aaca50d",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9903),
                            Description = "Desc 6",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 6",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "62242898-6ab0-4136-90d9-f52f9342d16b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9909),
                            Description = "Desc 7",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 7",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "ee08d9f0-6daf-4519-81f5-ac5941621ba2",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9915),
                            Description = "Desc 8",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 8",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "3f5bfb71-ba90-49e0-84c0-742743409bf4",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9923),
                            Description = "Desc 9",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 9",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "4d180de4-92ed-4376-b6b5-d24e5c80868f",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9930),
                            Description = "Desc 10",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 10",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c901d1da-caef-4b09-9828-3b4199f56ad6",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9964),
                            Description = "Desc 11",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 11",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "873ffc1b-e60b-4516-917a-c04388c6b8fd",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9970),
                            Description = "Desc 12",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 12",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "93ce7be8-0372-4486-be00-9a457cba3091",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9976),
                            Description = "Desc 13",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 13",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "738607a1-40fa-4aa7-a8e5-524b0684acfb",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9982),
                            Description = "Desc 14",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 14",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b9f669e3-0967-4943-8207-3a03c7a47bbd",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9988),
                            Description = "Desc 15",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 15",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "528b14cf-07be-46ad-a861-389ec4009791",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 366, DateTimeKind.Local).AddTicks(9994),
                            Description = "Desc 16",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 16",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "922c7247-0420-4a10-9947-4e60ef125d1e",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(2),
                            Description = "Desc 17",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 17",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c2bcc609-b761-413b-8d0e-e678c7d8075d",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(8),
                            Description = "Desc 18",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 18",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "dc34ad62-596d-47cc-8e8b-b526efd1f3da",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(14),
                            Description = "Desc 19",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 19",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "60ce1051-27c0-483a-9a01-b0896a240b81",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(20),
                            Description = "Desc 20",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 20",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "850cc054-af0b-4645-8b92-aa538eff8f08",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(26),
                            Description = "Desc 21",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 21",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "9dd9fc5a-ddb0-4776-94ea-19032b696968",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(32),
                            Description = "Desc 22",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 22",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "a948b42f-3346-40ed-b32e-528f64dbfb61",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(38),
                            Description = "Desc 23",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 23",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "f857d9d5-b613-4707-853c-fa97e9ab2ab0",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(44),
                            Description = "Desc 24",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 24",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "27962453-d280-4acd-93d7-7b767f9e4b47",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(51),
                            Description = "Desc 25",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 25",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "ebcc4014-7785-48a7-b44b-18613ee7bf7c",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(57),
                            Description = "Desc 26",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 26",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "95e402d9-a2c5-4f3e-b0a2-9d835fd5fae4",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(63),
                            Description = "Desc 27",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 27",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "92cde209-23be-4804-8dde-aefd471d2185",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(69),
                            Description = "Desc 28",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 28",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "9ae79647-eb01-4d53-9161-acf351c16eb8",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(75),
                            Description = "Desc 29",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 29",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "05eff5cf-b2ac-4df5-8b35-9bfbc7e5237a",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(81),
                            Description = "Desc 30",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 30",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "77540020-f545-4ccf-9889-d404196c01e2",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(87),
                            Description = "Desc 31",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 31",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b67186ce-31b2-4bc9-b328-ee64f283d70b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(92),
                            Description = "Desc 32",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 32",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "232285ab-2a55-4ff9-afdb-4634264a993e",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(100),
                            Description = "Desc 33",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 33",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "1acb8044-1b5c-492f-b798-949e8aa6fe35",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(106),
                            Description = "Desc 34",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 34",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "7ebf83c2-d525-4ead-b4fc-1291eac46dad",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(112),
                            Description = "Desc 35",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 35",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "2b323625-98b3-490c-a3d1-b1591041c657",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(138),
                            Description = "Desc 36",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 36",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "04224af0-784e-4bb8-9c9c-32a8b89a3eec",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(144),
                            Description = "Desc 37",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 37",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "361f2159-309a-4fec-b389-0b250de327c5",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(150),
                            Description = "Desc 38",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 38",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b15425e6-5fbc-4e2e-b487-41edc0f9c84c",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(156),
                            Description = "Desc 39",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 39",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "97b18269-8a6a-430e-808e-9a669e1cd8d8",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(162),
                            Description = "Desc 40",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 40",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "a4193c65-2d82-4e56-8f2b-c1879503679b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(170),
                            Description = "Desc 41",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 41",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "dcae6468-c01b-4213-a0ee-f94b2a694afc",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(176),
                            Description = "Desc 42",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 42",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "e44b0935-3176-478d-9f01-3fb77de25dd3",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(182),
                            Description = "Desc 43",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 43",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "a2073149-2e5e-4975-8ab0-a4dbf911fef7",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(188),
                            Description = "Desc 44",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 44",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "d43be53b-fd80-4b4b-8f00-1d6ef06b97bb",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(194),
                            Description = "Desc 45",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 45",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "dfb91686-9489-495a-b088-47c2a8891b5d",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(200),
                            Description = "Desc 46",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 46",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "5b0862e5-78fb-4b55-820c-97a9eed8bf62",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(206),
                            Description = "Desc 47",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 47",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "fe1eee9f-b4c8-48a7-9055-ccce71cde1cc",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(212),
                            Description = "Desc 48",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 48",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "3c408f9d-4db6-4f8e-9aa2-c0118805f0ee",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(220),
                            Description = "Desc 49",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 49",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "f3b6e116-b82b-47c8-bae4-04d137b3ab70",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(226),
                            Description = "Desc 50",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 50",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "745a05e5-5e83-4945-9eee-1d3ed83901c7",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(231),
                            Description = "Desc 51",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 51",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "bc08a35e-15e3-4b20-85a4-5302878f87a5",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(237),
                            Description = "Desc 52",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 52",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "921bfdb2-36af-45c1-af9e-4dbbf7a4bbd6",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(243),
                            Description = "Desc 53",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 53",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "fbbc291b-563c-4587-84fa-cee24666e8cc",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(249),
                            Description = "Desc 54",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 54",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "015f73e7-32b1-4754-ba45-8f7f5bd52d34",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(255),
                            Description = "Desc 55",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 55",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "6af6148d-b10a-4575-92a8-ea3996dd43bb",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(261),
                            Description = "Desc 56",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 56",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c2de7103-a6a3-428e-bf66-0d0c27b1caae",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(269),
                            Description = "Desc 57",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 57",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "a4f73457-1683-4d20-857a-fe444d35ce3b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(274),
                            Description = "Desc 58",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 58",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "7210a76e-ac1d-43cd-9147-c05e0fe453dc",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(281),
                            Description = "Desc 59",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 59",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "961f5915-706e-40c7-9031-d33229e3f599",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(286),
                            Description = "Desc 60",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 60",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "74d8f3fa-0bcb-4d0c-b4d4-c66fb9b3fde3",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(292),
                            Description = "Desc 61",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 61",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "7e5148a8-60fc-4787-83ff-64bda199b1b7",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(318),
                            Description = "Desc 62",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 62",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "56e64fc2-2274-4bf3-9479-0030d0c369ad",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(324),
                            Description = "Desc 63",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 63",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b3509e61-7df1-4f00-803e-9bd0c3baac4b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(330),
                            Description = "Desc 64",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 64",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "fa4408ca-3f03-4a70-bf30-26e8c6d6c7fc",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(338),
                            Description = "Desc 65",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 65",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "afc32103-1e8e-44e0-86bc-071600a2b550",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(344),
                            Description = "Desc 66",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 66",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c3f14093-baca-415c-8d42-7e6c74eed070",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(350),
                            Description = "Desc 67",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 67",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "97de5ad0-a283-487c-a8b9-4d413492455a",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(356),
                            Description = "Desc 68",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 68",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "e2f00b4d-36da-4ff0-abcf-b66909888d5b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(362),
                            Description = "Desc 69",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 69",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "ce1e17ea-1a04-4b88-8fa2-df491d6e0ba5",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(368),
                            Description = "Desc 70",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 70",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b2f01ff2-9cc7-44ea-bd45-8b8b568b82cb",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(374),
                            Description = "Desc 71",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 71",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "837e2de9-f91e-4ec8-a210-dd49bb023e78",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(380),
                            Description = "Desc 72",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 72",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "57d2872c-a6bf-487e-a291-7f686390e190",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(387),
                            Description = "Desc 73",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 73",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b0eabbfb-9bcf-46a3-a65e-9b0aebedb220",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(394),
                            Description = "Desc 74",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 74",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "0dfbbfef-192c-494c-95b9-0d24220c8397",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(400),
                            Description = "Desc 75",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 75",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "e1b1183f-a1c1-4ca7-b114-8340ad029876",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(406),
                            Description = "Desc 76",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 76",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c5b1dbff-6b77-4438-9122-9d425b21931f",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(411),
                            Description = "Desc 77",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 77",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "bcbe93b3-76c0-4170-9dbd-c451cc22586d",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(417),
                            Description = "Desc 78",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 78",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "28b2e60a-1cff-4176-8604-5385a1fe2f47",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(423),
                            Description = "Desc 79",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 79",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "d1930ed1-09d1-43d2-8f8d-a9659c1a32a4",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(429),
                            Description = "Desc 80",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 80",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b13d1d0b-9743-4bea-871e-b740a8a31dc8",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(437),
                            Description = "Desc 81",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 81",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "fa87af0f-2d7f-4e4a-b423-b8928a6af132",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(443),
                            Description = "Desc 82",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 82",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "f14148d0-7425-4b5c-abde-86916d6404d1",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(449),
                            Description = "Desc 83",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 83",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "ac0d2636-3e0c-432a-b6ce-a89658f415f2",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(455),
                            Description = "Desc 84",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 84",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "9078f414-329b-467a-b239-2bd796957285",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(460),
                            Description = "Desc 85",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 85",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "cda17a83-c1ec-45c1-8283-918b094b57aa",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(466),
                            Description = "Desc 86",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 86",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "2fd8e6d2-e97c-4fdb-a555-bb245a1d90a8",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(507),
                            Description = "Desc 87",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 87",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c28759a5-3046-4a94-9cd4-f21df1fd1afd",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(514),
                            Description = "Desc 88",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 88",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "40f2d5db-35db-484f-a60b-101c34a43d17",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(522),
                            Description = "Desc 89",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 89",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "79eea990-2178-42c0-ac88-76d4820b3510",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(528),
                            Description = "Desc 90",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 90",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "32106535-f3d6-4904-9ff7-d1a3c9c6b266",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(534),
                            Description = "Desc 91",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 91",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "a1465285-dde9-48b3-b45e-6035627e3a37",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(540),
                            Description = "Desc 92",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 92",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "9827206a-5428-429b-8f39-79b5b6ddce78",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(545),
                            Description = "Desc 93",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 93",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "3ec290cc-18dc-43bb-9be3-0757e21f8715",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(551),
                            Description = "Desc 94",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 94",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "76c18c23-eda5-4fa5-9d7f-69807a68586a",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(557),
                            Description = "Desc 95",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 95",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "0d7a72e3-a0a5-4a8d-909f-9ded86bb8c6d",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(563),
                            Description = "Desc 96",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 96",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "f06af473-b1e8-4b84-81e7-35be39948972",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(571),
                            Description = "Desc 97",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 97",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "fcf6e5dd-99a4-4055-a303-cd0d39f31b4e",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(577),
                            Description = "Desc 98",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 98",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "55e876eb-fa51-414a-a5bb-c10ac30590b4",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(583),
                            Description = "Desc 99",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 99",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "60752614-093a-4ec4-8414-a8dcb3ab4278",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(589),
                            Description = "Desc 100",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 100",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "ae7eda05-f452-4732-bb21-5f72f0210b95",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(595),
                            Description = "Desc 101",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 101",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "3c07d023-da32-4216-aab5-4236a56ad817",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(601),
                            Description = "Desc 102",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 102",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b94900e4-5bc6-4709-b6b8-dbf6c0999b59",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(607),
                            Description = "Desc 103",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 103",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "950aa8d8-f126-4aaa-9de6-8eedd251a983",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(613),
                            Description = "Desc 104",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 104",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "de43a098-8080-4e52-a9b6-4cf215536187",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(620),
                            Description = "Desc 105",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 105",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "b03f7031-2489-40ec-bfca-e1b8e7039cb7",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(626),
                            Description = "Desc 106",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 106",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "9a22389f-b38f-4252-8926-888660c0594c",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(632),
                            Description = "Desc 107",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 107",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "f81ff09c-5e0c-4613-8df0-eef7c1fae2f8",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(638),
                            Description = "Desc 108",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 108",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "0d86bf31-3663-461e-b54a-b5c1b3afb633",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(644),
                            Description = "Desc 109",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 109",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "4df51eec-fd03-4a88-968b-6512bd5da27e",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(650),
                            Description = "Desc 110",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 110",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "2cc2c558-34af-4a11-9133-d8786aabbce3",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(656),
                            Description = "Desc 111",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 111",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "3ef0639f-2d5c-4d99-bf02-2e1330f3530b",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(662),
                            Description = "Desc 112",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 112",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "75af384b-9eba-435f-806e-17e6e36d76d0",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(689),
                            Description = "Desc 113",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 113",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "1c50ec4d-a824-470d-ab9e-149f8afe2d07",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(695),
                            Description = "Desc 114",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 114",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c919875d-f915-4816-83af-be5aa7be70a6",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(701),
                            Description = "Desc 115",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 115",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "19b5966f-1010-4c42-8888-8a761e035f9d",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(707),
                            Description = "Desc 116",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 116",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "e119790c-a04e-451a-864a-5e7b59628b77",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(713),
                            Description = "Desc 117",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 117",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "8c8b2a1b-7db3-4d6a-b58d-9f3a484d1d44",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(719),
                            Description = "Desc 118",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 118",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "c488fef2-b81a-4b3d-b79c-fa0b6359dbd6",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(725),
                            Description = "Desc 119",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 119",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "0eee59c8-5dcb-46d5-a976-170e6b56ac08",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(731),
                            Description = "Desc 120",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 120",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "0e4df585-63d9-4bfe-b4b2-02f86463a97c",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(738),
                            Description = "Desc 121",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 121",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "e88f4f7c-3150-4719-9214-f65d239d052f",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(745),
                            Description = "Desc 122",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 122",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "5d98073a-f799-4053-8372-55548bd2dbd4",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(750),
                            Description = "Desc 123",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 123",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "d295f373-c33c-48e0-aea2-0acb1e72dc0f",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(756),
                            Description = "Desc 124",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 124",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "991de8c9-de78-4e16-9cd9-c8eafc230c31",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(762),
                            Description = "Desc 125",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 125",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "a8cd41a2-fc72-4a4c-8948-aca0bcbac937",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(768),
                            Description = "Desc 126",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 126",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "556e6e96-102f-475e-a6d7-e590392a063a",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(774),
                            Description = "Desc 127",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 127",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "59cde79e-62a5-473f-83b6-3ff36d7ac57e",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(780),
                            Description = "Desc 128",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 128",
                            Type = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = "5de2b66b-910e-451c-8ad8-de3cae0321c6",
                            CreateDate = new DateTime(2023, 5, 9, 23, 58, 41, 367, DateTimeKind.Local).AddTicks(788),
                            Description = "Desc 129",
                            RelatedProgLanguages = "Cpp",
                            Title = "Title 129",
                            Type = 0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("TopSolution.Models.SiteUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("CommunityPoints")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.HasDiscriminator().HasValue("SiteUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopSolution.Models.Comment", b =>
                {
                    b.HasOne("TopSolution.Models.SiteUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("TopSolution.Models.Topic", "Topic")
                        .WithMany("Comments")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TopSolution.Models.Topic", b =>
                {
                    b.HasOne("TopSolution.Models.SiteUser", "Owner")
                        .WithMany("Topics")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TopSolution.Models.Topic", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TopSolution.Models.SiteUser", b =>
                {
                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
